train: E:\Programming\cv-25-project\dataset\train\images
val: E:\Programming\cv-25-project\dataset\val\images
test: E:\Programming\cv-25-project\dataset\test\images
names:
  0: skier
  1: snowboarder
