path: D:\Programming\School\cv-25\cv-25-project\dataset
train: train\images
val: val\images
test: test\images

nc: 2

names: 
  0: "skier"
  1: "snowboarder"

augment:
  flipud: 0.15 # Flippar bilder vertikalt ibland
  fliplr: 0.5 # Flippar bilder horisontellt ibland
  mosaic: 1.0 # Mosaic augmentation (kombinerar 4 bilder)
  hsv_h: 0.015 # Färgjusteringar
  hsv_s: 0.7
  hsv_v: 0.4
  mixup: 0.2 # Mixup augmentation

optimizer:
  type: 'adam'
  lr0: 0.001
  momentum: 0.9
  weight_decay: 0.0005